version: '3'
services:
  laravel:
    build:
      context: 'bin/${BIN}'
      dockerfile: 'Dockerfile-${PHP_VERSION}'
      args:
        - 'BIN=${BIN}'
        - 'USER=${USER}'
        - 'GROUP=${GROUP}'
        - 'ERRORS=${PHP_ERRORS}'
        - 'VERSION=${PHP_VERSION}'
        - 'XDEBUG=${XDEBUG}'
        - 'LARAVEL_VERSION=${LARAVEL_VERSION}'
        - 'EXTENSIONS=${EXTENSIONS}'
    volumes:
      - '${APP_PATH}:${APP_PATH_LARAVEL}${APP_CONTAINER_FLAG}'
    ports:
      - '${LARAVEL_HTTP_PORT}:80'
volumes: {}